### PR TITLE
i18n(ES) first version

### PR DESCRIPTION
**Pull request by joebordes**

### CODE REVIEW

**Comment by joebordes** [comment]
I would appreciate if you could add the `hacktoberfest-accepted` label

**Review by mengshukeji — APPROVED** [review]
good

**Comment by joebordes** [comment]
I'm glad this was useful. Any chance you can add the `hacktoberfest-accepted` label?

**Comment by wbfsa** [comment]
> I'm glad this was useful. Any chance you can add the `hacktoberfest-accepted` label?

Ok, thank you for your contribution!?:)

**Pull request merged**
